### ISSUE TITLE
Possible tracking logic bugs

### ISSUE THREAD

**Issue by pkmnfrk** [Hamsda/OoTRMapTracker#19]
Hi, excellent work overall on this thing! However, I think there are a handful of bugs in the logic. Here are the ones I noticed:

1. If there is a way to get to the "Lava Room Grotto" Deku Scrubs in Goron City without the Hookshot, I can't think of it. And yet, they appear accessible without it

2. The Gold Skulltula at Castle Storms Grotto should be locked behind waking up Talon (getting the Weird Egg, I guess)

**Comment by pkmnfrk** [comment]
And then there's this:

![oot_items](https://user-images.githubusercontent.com/1333816/46514954-fb999f80-c82e-11e8-87f7-1e896beb6b4b.PNG)

I'm not entirely sure what is going on here. I honestly can't figure out why it thinks half the Shadow Temple items are inaccessible, especially since I just went in and started collecting them (eg, first thing I did was go in and bead Dead Hand for the Hover Boots Chest)

I'm using EmoTracker 2.1.0.2, and here's the save file:

[oot mq.zip](https://github.com/Hamsda/OoTRMapTracker/files/2448874/oot.mq.zip)

**Comment by pkmnfrk** [comment]
RE Goron City: I couldn't find the spot to summon the second block in order to cross via Hover Boots, so I'm not sure how to cross.

RE Talon: You're not wrong, but if you go there and try, the hole just won't open. I think it's an engine thing.

RE Shadow Temple: Interesting, you are correct that the key counts aren't correct yet, at least. I completed the Shadow Temple just after I posted the screenshot, and found another Shadow Temple key within. Glad to hear this is getting fixed.

Incidentally, kudos on keeping up with the randomizer so quickly, it feels like it changes every day!

**Comment by Hamsda** [comment]
The second SoT block is very close to the opposite ledge. ![This picture shows it quite nicely.](https://jegged.com/img/Games/Legend-of-Zelda-Ocarina-of-Time/Walkthrough/0788-Goron-City-Stone-of-Time.png)

I'll have to test the SoS grotto, I was not aware. Maybe the rando devs can actually "fix" that, because that surely is not considered in logic.

**Comment by Hamsda** [comment]
Hmm I could spawn the SoS grotto near Talon without waking him up, so I don't see the issue here. Are you sure you stood in the correct spot, near the tree?

Shadow Temple key counts are fixed, will push the update soon.
