### ISSUE TITLE
Reusing icons from your repository

### ISSUE THREAD

**Issue by Feneg** [Hamsda/OoTRMapTracker#25]
Not an issue, but Github doesn't seem to offer any other way to contact you.

I've written a similar (but standalone) program a while back and in its latest iteration I use icons from your repository. I'm now considering putting the code here on Github -- which would be the first time it sees a public release. Which is why I'd like to ask whether there are any issues you might want to raise or any wishes regarding crediting.

**Comment by Hamsda** [comment]
All good, we have been sharing these icons freely all the time, since many of them are just from in game sprites.

**Comment by Feneg** [comment]
Thanks. I'll probably put up the repository on the weekend. Cheers.
