### ISSUE TITLE
Possible Tracking Error with Ruto's Letter

### ISSUE THREAD

**Issue by katherto** [Hamsda/OoTRMapTracker#29]
Going through a hellsanity for the fun of it I noticed this possible issue pop up today. I found Ruto's Letter, and upon tracking the item it shows Bean Patch skulltulas as being attainable. This would normally make sense except I have no way of showing the letter to King Zora (no bombs, ocarina, lullaby, or scale). Also to note this is the only "bottle" I've found.

Would it make more sense to include the bottle logic after ticking off "Move King Zora?"

**Comment by Hamsda** [comment]
Hmmm... not sure how I feel about this 🤔 
I'll probably have to implement it and see how it would work out on the actual tracker...

**Comment by katherto** [comment]
Understandable. It might also be relevant to mention this happens with Big Poe bottles too. Only way to empty it is sell it to the poe merchant. So that one would be locked behind Master Sword and ticking off "Big Poes." I've also found tracking Big Poe bottles odd since they don't open up that check in the first place.

Not a huge ordeal or problem but just another level of polish perhaps.  All this ends up not mattering if a second bottle is found anyway.

**Comment by Hamsda** [comment]
Yeah the only bottle content that has an actual effect is rutos letter. The rest of them are mainly for fun to keep track of what your bottle started with (at least thats how I use it, maybe some people use it to keep track of current contents 🤷‍♂️ ).
But yeah, I'll see how changing them feels.

**Comment by Hamsda** [comment]
Okay so I pushed an update to the dev branch that feels pretty decent to me.
Still have a bit of work to do for this one, but might be coming in the next few days.
If you want to try it out early, you can grab the dev branch to test it.

**Comment by Hamsda** [comment]
Ok, now pushed to master, you should get the update in EmoTracker.

Big Poe bottles still won't actually have any function.
But being able to reach king zora as child/child ZF will make rutos letter bottles actually count as a free bottle and being able to reach poe dude (so having sword2) will make those count.

**Comment by alemonplays** [comment]
Another error i`ve found is that as Adult Link, the Ice Cavern only appears as obtainable if you have Ruto's Letter in your inventory. (Tested with Keysanity Map Tracker)
I don't know why,

**Comment by Hamsda** [comment]
Because you need to hand in the letter unless open fountain is selected.
