### ISSUE TITLE
Shadow Temple Logic Inconsistency

### ISSUE THREAD

**Issue by katherto** [Hamsda/OoTRMapTracker#32]
As adult with full Shadow Temple access and completion possible, Falling Spikes Upper is shown as red due to no strength upgrade. With the recent accessible change of allowing the clip these two chests should be Yellow and possible correct?

I could understand if the tracker doesn't follow accessible logic to the tee but wanted to point this out in case it was an oversight due to recent rule changes.

**Comment by Hamsda** [comment]
Oh yeah, I haven't changed those to sequence breaks yet, thanks for the reminder.

**Comment by Hamsda** [comment]
Ok, just pushed a small update that includes the recent changes.

And yeah, I try to follow the logic of the randomizer in general and mark sequence breaks that are allowed in the accessible rule set.

**Comment by katherto** [comment]
Awesome. I wasn't sure if that was the case if tracker logic followed closely with the accessible rules or not. Thanks for doing this! I'll keep my eye open for anything else I come upon to help you out.

**Comment by Hamsda** [comment]
Yeah there might be a few use cases for flame storage that I can't think off, but thanks for the report! :)
