### ISSUE TITLE
Gauntlets and Goron bracelet should be split

### ISSUE THREAD

**Issue by thefellow3j** [Hamsda/OoTRMapTracker#39]
You should split the gauntlets from the Goron bracelet. You can't pick up bomb flowers without the bracelet, even as Adult Link.

**Comment by Hamsda** [comment]
I don't think you quite understand how the strength upgrades work:
Once you have bracelet you can lift bomb flowers. But silver gauntlets are just an upgrade from there, you can still pick up bomb flowers.
