### ISSUE TITLE
Kakarikos Village Graveyard Items only at night

### ISSUE THREAD

**Issue by alemonplays** [Hamsda/OoTRMapTracker#57]
Dampes Gravedigging Tour and the Shield Grave Chest are only available at night. But the Tracker don't show the (N) at the end of the sub-description. Sincerely i only saw the (N) at the Skulltulas so i don't know if this was intended or just forgotten to be add.

**Comment by darkangel93x** [comment]
because you can always do them as adult.  its not a "only night" thing :)

**Comment by alemonplays** [comment]
Ohhh ok. That makes sense. 😅
Didn't remembered that because I'm doing only a vanilla playthrough. 

IF (and this is also a suggestion I'd like to see) Hamsda decides to do a vanilla tracker, I hope he remembers this issue. I'll close this issue for now since the tracker is focused on randomizer playthroughs.

**Comment by Hamsda** [comment]
I mean the gravedigging tour can't be done as adult. But it is also not the entire night. tbh the `(N)` is only on skulls and I don't think I will change that.

**Comment by alemonplays** [comment]
Yeah. I thought so. When I saw that the Richard Dog Quest didn't had it either, I figured that this was intended so. Thx anyways :)
