### ISSUE TITLE
Possible to complete MQ Forest Temple with 4 Keys using the Longshot and Song of Time 

### ISSUE THREAD

**Issue by lKomus** [Hamsda/OoTRMapTracker#61]
Hello,

Currently, in this temple, the tracker puts the basement chest and the boss as inaccessible if you have 4 or 5 small keys. But it is possible to skip a portion of the temple early on if you have these two items. You use the longshot on the Garden chest then use the Song of Time on the Time blocks to access the checkerboard room, you can use a small key and kill the green ghost. Then, you do the temple as usual until you've killed the remaining ghosts. Since there are no chests, there is no need to continue down the path after the second ghost, all the chests can be accessed from there, only the basement chest and the boss is left. You can backtrack and kill the purple ghost to finish the dungeon.

Unless I'm mistaken in my explanation, the basement chest and the boss should be marked as yellow.

I am using version 2.3.3.7, but I haven't seen any changes related to this in the changelogs, so I believe this is still receivable.

![EmoTracker_PvmuhU6dnm](https://user-images.githubusercontent.com/4800879/57741915-28643e00-76bf-11e9-9a57-9de3a793f153.jpg)

**Comment by Hamsda** [comment]
Yeah that sequence break (or rather a similar version) is in the non MQ variant and I have just missed this one.
Will add soon :)

**Comment by Hamsda** [comment]
Should be in now.
