### ISSUE TITLE
Vanilla Water Temple key requirements are incorrect

### ISSUE THREAD

**Issue by BeeLuigi** [Hamsda/OoTRMapTracker#68]
The lock that was removed in Water Temple isn't put back in keysanity (unlike it's Fire Temple counterpart). The removal isn't handled in the logic files of the randomizer, but rather in ItemPool.py (yes I agree it's dumb). So the key requirements should be 1 lower than what's in "Water Temple.json"

**Comment by Hamsda** [comment]
Oh...
I recently noticed that my tracker still wanted all 6, then went and looked in the logic files and saw that it's using the old numbers there as well. Even though I knew that Dark Link and BK obviously only require 5. I should've just asked about it <.<
Will fix soon.
